// Every term is written twice: `short` is the one-line answer a beginner needs,
// `long` is the fuller explanation. `level` says who needs it first.
// b = basics, i = intermediate, a = advanced.
(function (g) {
  'use strict';

  const CATS = ['The basics', 'Prices and costs', 'Orders', 'Risk and money', 'Sessions and timing',
                'Pairs and markets', 'News and events', 'Reading charts', 'Trading styles', 'In this app'];
  const LEVELS = { b: 'Basics', i: 'Intermediate', a: 'Advanced' };

  // [term, level, category, short, long, example, see-also ids]
  const RAW = [
    // ---- The basics
    ['Forex (FX)', 'b', 0, 'The market where currencies are swapped for each other.',
      'It is the largest financial market in the world and has no central exchange. Banks, companies, funds and individual traders trade over networks, which is why it runs around the clock on weekdays.'],
    ['Currency pair', 'b', 0, 'Two currencies quoted together, such as EUR/USD.',
      'The price tells you how much of the second currency you need to buy one unit of the first. You never buy a currency alone. You buy one and sell the other.',
      'EUR/USD at 1.1000 means 1 euro costs 1.10 US dollars.', ['base-and-quote-currency']],
    ['Base and quote currency', 'b', 0, 'In EUR/USD, EUR is the base and USD is the quote.',
      'The base currency is the one you are buying or selling. The quote currency is the one the price is written in. Buying the pair means buying the base and selling the quote.'],
    ['Buy and sell (long and short)', 'b', 0, 'Buying bets the base currency will rise. Selling bets it will fall.',
      'Buying is called going long. Selling is called going short. In forex you can profit either way, because every trade is one currency against another.',
      'Selling EUR/USD makes money if the euro falls against the dollar.'],
    ['Broker', 'b', 0, 'The company that gives you access to the market and holds your account.',
      'Brokers differ in spreads, fees, leverage and how they fill orders. Choose one regulated where you live.'],
    ['Demo account', 'b', 0, 'A practice account with fake money and real prices.',
      'Use it to learn the platform and test ideas before risking real money. Demo fills can be cleaner than real ones, so treat results as a guide, not proof.'],
    ['Server time (chart time)', 'b', 0, 'The clock your broker\'s charts use. It may not match your local time.',
      'Candles open and close by this clock, so check it before you use session times. Exness says its MT4 and MT5 platforms run on GMT+0 and that this cannot be changed. Many other brokers use GMT+2 or GMT+3. TradingView follows whatever timezone you set on the chart. In this app, choose your broker under Settings.'],
    ['GMT and UTC', 'b', 0, 'The world reference time. Ghana uses it all year.',
      'It never changes for daylight saving. Forex sessions are often quoted in it because it stays fixed.'],
    ['Daylight saving time (DST)', 'i', 0, 'When clocks move an hour. It shifts session times on your clock.',
      'The UK, US and Australia change on different dates, so session hours move on your clock twice a year, and the London and New York overlap briefly stretches in between.',
      'In late October the UK moves its clocks back a week before the US does, so for that week London and New York overlap for 5 hours (12:00 to 17:00 GMT) instead of the usual 4.'],

    // ---- Prices and costs
    ['Pip', 'b', 1, 'The standard small step of price. 0.0001 on most pairs, 0.01 on yen pairs.',
      'Profit and loss are usually counted in pips. It is the yardstick for how far price has moved, how wide a spread is and how far away a stop-loss sits.',
      'EUR/USD moving from 1.1000 to 1.1010 has moved 10 pips.', ['pip-value', 'lot']],
    ['Pipette (fractional pip)', 'i', 1, 'One tenth of a pip. The fifth decimal place on most pairs.',
      'Many brokers quote to a pipette, so you see prices like 1.10234. The last digit is the pipette.'],
    ['Lot', 'b', 1, 'The size of a trade. One standard lot is 100,000 units.',
      'A mini lot is 10,000 units and a micro lot is 1,000. A bigger lot makes each pip worth more money, for wins and for losses.',
      'On EUR/USD one pip is about $10 on a standard lot, $1 on a mini lot and $0.10 on a micro lot.', ['pip-value']],
    ['Pip value', 'i', 1, 'How much money one pip is worth at your trade size.',
      'It depends on the pair, the lot size and your account currency. Work it out before you trade so you know what your stop-loss really risks. The Calculator tab does this for you and shows the working.', null, ['position-size', 'contract-size']],
    ['Contract size', 'i', 1, 'How many units of the base currency one standard lot controls.',
      'For forex pairs one lot is normally 100,000 units. Gold is usually 100 ounces per lot, but this varies by broker, so check your account. It is why the same lot size risks very different amounts on different instruments.'],
    ['Minimum lot and lot step', 'i', 1, 'The smallest trade your account allows, and the smallest change in size.',
      'A common setting is a minimum of 0.01 lots in steps of 0.01, but accounts differ. If your risk budget is smaller than what the minimum lot risks, you cannot trade that setup at your chosen risk. The calculator always rounds down, never up.'],
    ['Bid and ask', 'b', 1, 'Bid is the price you can sell at. Ask is the price you can buy at.',
      'The ask is always a little higher than the bid. The gap between them is the spread.',
      'Bid 1.10000, ask 1.10020.', ['spread']],
    ['Spread', 'b', 1, 'The gap between the buy and sell price. It is a built-in cost.',
      'You start every trade slightly behind, because you buy at the higher price and sell at the lower one. The price must move by the spread before you break even. Spreads are smallest when many traders are active, and widest when the market is quiet or news lands.',
      'Bid 1.10000 and ask 1.10020 is a 2 pip spread.', ['bid-and-ask', 'commission', 'liquidity']],
    ['Commission', 'i', 1, 'A fixed fee some accounts charge per lot, on top of a much tighter spread.',
      'Accounts advertising very low spreads often charge commission. To compare accounts fairly, add the spread cost and the commission together.'],
    ['Slippage', 'i', 1, 'Getting a different price from the one you clicked.',
      'It happens when the price moves between your order and its fill, most often in fast news moves or thin markets. It can work for you or against you.'],
    ['Execution', 'i', 1, 'How your broker fills your order: speed and how close to your price.',
      'Good execution means quick fills near the price you saw. It matters most for short trades and around news.'],
    ['Tick and tick volume', 'i', 1, 'A tick is one price update. Tick volume counts them.',
      'Forex has no central exchange, so real trading volume is not public. Tick volume rises and falls with activity and is a fair guide to how busy the market is.'],

    // ---- Orders
    ['Market order', 'b', 2, 'Buy or sell right now at the best available price.',
      'It fills at once, but you accept whatever the price is at that moment, including slippage.'],
    ['Limit order', 'b', 2, 'An order to buy lower or sell higher than the current price.',
      'It waits until price reaches your level and fills only at that price or better.',
      'Price is 1.1000. A buy limit at 1.0980 fills only if price falls to 1.0980.', ['pending-order']],
    ['Stop order (buy stop, sell stop)', 'i', 2, 'An order to buy above, or sell below, the current price once price gets there.',
      'Used to enter when price breaks out in a direction. It becomes a market order when triggered, so slippage is possible.', null, ['breakout']],
    ['Pending order', 'i', 2, 'An order waiting for price to reach a level before it activates.',
      'Limit orders and stop orders are pending orders. You can place them ahead of time, for example before a session opens.'],
    ['Stop-loss (SL)', 'b', 2, 'An order that closes a trade at a set loss to protect you.',
      'You decide the price where the idea is wrong and let the broker exit for you. Without one, a single bad move can cost far more than planned. In fast markets it can fill worse than the price you set (slippage).',
      'Buy at 1.1000 with a stop-loss at 1.0980: the trade closes at about a 20 pip loss.', ['risk-per-trade', 'slippage']],
    ['Take-profit (TP)', 'b', 2, 'An order that closes a trade when it reaches your profit target.',
      'It locks in a gain automatically so you do not have to watch the screen.'],
    ['Trailing stop', 'i', 2, 'A stop-loss that follows price as it moves in your favour.',
      'It only moves in your favour and never back, locking in profit while giving the trade room to run.'],

    // ---- Risk and money
    ['Leverage', 'b', 3, 'Borrowing from your broker so a small deposit controls a large trade.',
      'With 1:100 leverage, every 1 of your money controls 100 in the market. It magnifies profits and losses equally. Maximum leverage varies by country and broker. Lower is safer.',
      '$100 at 1:100 controls a $10,000 position. A 1% move against you loses the whole $100.', ['margin']],
    ['Margin', 'b', 3, 'The part of your money the broker sets aside to keep a trade open.',
      'It is not a fee. It is locked while the trade is open and released when you close it.', null, ['free-margin', 'margin-call']],
    ['Balance and equity', 'b', 3, 'Balance is your money without open trades. Equity is balance plus or minus open profit or loss.',
      'Equity changes every second while a trade is open. Watch equity, not balance, to know where you really stand.'],
    ['Free margin', 'i', 3, 'The money in your account that is not tied up as margin.',
      'It is equity minus used margin. It is what you have left to open new trades or absorb losses.'],
    ['Margin level', 'i', 3, 'Equity divided by used margin, shown as a percentage.',
      'Brokers use it to decide when to warn you and when to close trades. A falling margin level means your safety cushion is shrinking.'],
    ['Margin call', 'b', 3, 'A warning that your account is running low on funds to support open trades.',
      'When margin level falls to your broker\'s set level, you need to add money or close trades.', null, ['stop-out']],
    ['Stop-out', 'i', 3, 'The point where the broker automatically closes your trades.',
      'It happens when losses push margin level below the broker\'s stop-out level. You keep the loss and lose the chance of waiting for recovery.'],
    ['Risk per trade', 'b', 3, 'The amount of money you accept losing if the trade is stopped out.',
      'Many traders cap it at a small share of the account, commonly 1 to 2 percent. That is a widely used guideline, not a rule. Position size is then worked backwards from your stop-loss distance.',
      'Account $1,000, risk 1%: the most you lose on one trade is $10.', ['position-size']],
    ['Position size', 'i', 3, 'How big the trade is, chosen so the stop-loss risks only what you planned.',
      'Risk amount divided by (stop distance in pips multiplied by pip value per lot) gives the lot size, rounded down to the lot step. The Calculator tab does this, counts the spread as extra risk, and shows every step.',
      'Risk $50 with a 25 pip stop, and $1 per pip per mini lot: 50 ÷ (25 × 1) = 2 mini lots.'],
    ['Risk-reward ratio', 'i', 3, 'How much you aim to make compared with how much you risk.',
      'Risking 20 pips to make 40 is 1:2. A higher ratio lets you be wrong more often and still come out ahead, but the target must be realistic.'],
    ['Win rate', 'i', 3, 'The share of your closed trades that made money.',
      'It means little alone. A 40% win rate can be profitable with a good risk-reward ratio, and a 70% win rate can lose money with a poor one. On a small number of trades it is also very unreliable: 4 wins in 10 trades could really mean anything from about 17% to 69%. The journal shows that range.', null, ['sample-size', 'expectancy']],
    ['Sample size', 'i', 3, 'How many trades a statistic is based on. Fewer trades means less you can trust it.',
      'A win rate from 8 trades is mostly luck. The journal calls under 10 trades "too few to judge", 10 to 29 "early", and 30 or more "more reliable". Even then it is a guide, not a promise.'],
    ['R multiple', 'i', 3, 'A trade\'s result measured in units of the risk you took. Risk 10 and make 20, and it is +2R.',
      'It lets you compare trades of different sizes. A loss that hits your stop is about -1R. Averaging your R across many trades shows whether your method makes money, whatever the lot sizes were.',
      'Planned risk 25, result -25 is -1R. Result +50 is +2R.', ['expectancy']],
    ['Expectancy', 'a', 3, 'The average amount you make or lose per trade over many trades.',
      'It is total net result divided by the number of trades, or the average R. Positive means the method has made money on average so far. It needs many trades to be reliable.'],
    ['Profit factor', 'a', 3, 'Total won divided by total lost. Above 1 means winners outweighed losers.',
      'A profit factor of 2 means you won twice as much money as you lost. It ignores how many trades that took, so read it alongside the sample size.'],
    ['Trading journal', 'b', 3, 'A record of every trade and why you took it, so you can learn from what you actually do.',
      'Memory flatters. A journal records the pair, time, result and whether you followed your plan. After enough trades it shows patterns you cannot see day to day. The Journal tab keeps yours on this device, and you should back it up.'],
    ['Drawdown', 'i', 3, 'How far your account has fallen from its highest point.',
      'A 20% drawdown needs a 25% gain to get back. Watching drawdown keeps losing streaks survivable.'],
    ['Hedging', 'a', 3, 'Holding opposite trades to reduce risk.',
      'It can freeze a loss rather than remove it, and both trades still pay spreads. Some brokers and regions restrict it.'],
    ['Swap (rollover)', 'i', 3, 'A fee or credit for keeping a trade open past the daily cut-off.',
      'It reflects the interest-rate difference between the two currencies. The daily cut-off is usually 5 pm New York time, and many brokers charge triple swap on Wednesday to cover the weekend.'],
    ['Carry trade', 'a', 3, 'Buying a currency that pays high interest, funded by selling one that pays low.',
      'You earn the swap difference while price holds. It can unwind fast when markets turn nervous.', null, ['risk-on-and-risk-off']],

    // ---- Sessions and timing
    ['Trading session', 'b', 4, 'A stretch of hours when a major financial centre is open.',
      'Forex has four: Sydney, Tokyo, London and New York. When more centres are open, more traders are active.', null, ['overlap']],
    ['Overlap', 'b', 4, 'Hours when two sessions are open together.',
      'More traders means more volume and usually tighter spreads. London plus New York is the busiest overlap of the day.'],
    ['Asian session (Sydney and Tokyo)', 'b', 4, 'Quieter hours led by yen, Australian and New Zealand dollar pairs.',
      'Moves are usually smaller and price often moves sideways. The range set here is what London often breaks out of.'],
    ['London session', 'b', 4, 'The biggest session by volume. Euro and pound pairs are the most active.',
      'About 08:00 to 17:00 London time. Volume and volatility jump at the open.'],
    ['New York session', 'b', 4, 'US data and dollar pairs. Strongest in its first hours, while London is still open.',
      'About 08:00 to 17:00 New York time. Activity falls after London closes.'],
    ['Liquidity', 'b', 4, 'How easily you can buy or sell without moving the price.',
      'High liquidity means many buyers and sellers, so trades fill quickly and close to the price you see, and spreads are tight. Low liquidity means wider spreads and jumpier prices.'],
    ['Volatility', 'b', 4, 'How much and how fast prices move.',
      'High volatility offers bigger chances and bigger risks. It usually rises during overlaps and news, and falls when few traders are active.'],
    ['Dead zone', 'i', 4, 'The quiet gap after New York closes and before Asia gets going.',
      'Spreads widen and price often drifts. Many brokers also roll to the next trading day around this time.'],
    ['Bank holiday', 'b', 4, 'A day when a country\'s banks are shut. Trading in its currency is thinner.',
      'Forex still trades on a holiday, but with fewer participants, so spreads are wider and moves can be erratic. Some brokers also change their hours. This app tracks holidays for the US, UK, euro area, Japan and Australia.', 'On US Thanksgiving, dollar pairs are thin even though London is open.'],
    ['Rollover window', 'i', 4, 'The minutes around 5 pm New York when spreads often widen.',
      'Brokers roll open positions to the next trading day at 5 pm New York time. Liquidity thins and spreads can widen sharply from about 16:55 to 17:15 New York time, and stops can be hit by a spread spike. Many traders avoid new entries then.', null, ['swap-rollover']],
    ['Home market', 'b', 4, 'The session where a currency trades most, such as New York for the US dollar or Tokyo for the yen.',
      'A pair trades best when both of its currencies have their home market open. EUR/USD is busiest when London and New York overlap. USD/JPY has only one side open in most of the day.'],
    ['Conditions score', 'i', 9, 'A score out of 100 for how good the trading conditions are for a pair over the next few hours.',
      'It rewards pairs whose two currencies both have their home markets open, that usually cost less, and that have no high-impact news, and it takes points away for news. It measures conditions only. It does not predict direction, and a high score is not a reason to trade.', null, ['home-market']],
    ['Gap', 'i', 4, 'A jump in price with no trading in between.',
      'Most often seen at the Sunday open after news over the weekend. A stop-loss can fill at a worse price than you set when price gaps through it.'],
    ['London fix', 'a', 4, 'A benchmark exchange rate set at 4 pm London time.',
      'Large funds trade at the fix, which can cause a burst of movement around it.'],

    // ---- Pairs and markets
    ['Major pair', 'b', 5, 'A pair that includes the US dollar and another large currency.',
      'EUR/USD, GBP/USD, USD/JPY, USD/CHF, AUD/USD, USD/CAD and NZD/USD. They trade the most and usually cost the least.'],
    ['Cross pair', 'b', 5, 'A pair that does not include the US dollar, such as EUR/GBP.',
      'Crosses usually have wider spreads than majors.'],
    ['Exotic pair', 'i', 5, 'A pair with a major currency and a smaller economy\'s currency.',
      'Examples: USD/MXN, USD/ZAR. Spreads are wide and prices can jump.'],
    ['Gold (XAU/USD)', 'b', 5, 'The price of one ounce of gold in US dollars.',
      'XAU is gold\'s market code. It is not a currency pair, but brokers list it beside them. Moves are large compared with most pairs, so the same lot size risks more money.'],
    ['US dollar index (DXY)', 'i', 5, 'A score of the dollar against a basket of six major currencies.',
      'A rising DXY means the dollar is strengthening broadly. Traders watch it for the dollar\'s general direction.'],
    ['Correlation', 'i', 5, 'How closely two pairs move together.',
      'EUR/USD and GBP/USD often move the same way. Trading both can double your risk on one idea.'],
    ['Safe haven', 'i', 5, 'An asset people move to when markets are scared.',
      'The US dollar, Japanese yen, Swiss franc and gold are common examples.'],
    ['Risk-on and risk-off', 'i', 5, 'Risk-on: traders feel confident. Risk-off: they feel nervous.',
      'In risk-on, currencies such as AUD and NZD tend to rise. In risk-off, safe havens such as the yen tend to rise.'],

    // ---- News and events
    ['Economic calendar', 'b', 6, 'A schedule of upcoming data releases and events.',
      'Check it before you trade. High-impact releases can widen spreads and move price fast. The Now tab shows the next 24 hours, in your time, and warns you before high-impact news.', null, ['impact-rating-high-medium-low', 'forecast-previous-and-actual']],
    ['Impact rating (high, medium, low)', 'b', 6, 'How much a release usually moves the market. High moves it most.',
      'Calendars rate each event. High-impact ones, such as interest-rate decisions, inflation and US jobs, often cause fast moves and wide spreads. Low-impact ones usually pass unnoticed. The rating is a guide: a surprise in a low-impact release can still move price.'],
    ['Forecast, previous and actual', 'b', 6, 'Forecast is what analysts expect. Previous is the last result. Actual is what came out.',
      'Markets move on the surprise, the gap between actual and forecast, more than on the number itself. A strong number that was expected can do little. A small miss can move price a lot.',
      'US jobs forecast 90K. If 160K is reported, that is a big positive surprise for the dollar.'],
    ['High-impact news', 'b', 6, 'A release likely to move prices sharply.',
      'Spreads widen and price can jump past stops. Some traders stay out for a few minutes either side.'],
    ['Central bank', 'b', 6, 'The institution that controls a country\'s money and interest rates.',
      'Examples: the US Federal Reserve, the European Central Bank, the Bank of England and the Bank of Japan. Their decisions move currencies more than almost anything else.'],
    ['Interest rate decision', 'i', 6, 'When a central bank raises, cuts or holds its rate.',
      'Higher rates usually attract money and lift a currency, but markets react to what was expected. A surprise moves prices the most.'],
    ['FOMC', 'i', 6, 'The US Federal Reserve committee that sets US interest rates.',
      'It meets about eight times a year. Its decision, statement and press conference cause some of the biggest dollar moves.'],
    ['Hawkish and dovish', 'a', 6, 'Hawkish leans towards higher rates. Dovish leans towards lower rates.',
      'Traders read the tone of central bank speeches to guess the next move. A hawkish surprise usually lifts the currency.'],
    ['NFP (Non-Farm Payrolls)', 'i', 6, 'The US monthly jobs report.',
      'Released at 08:30 New York time, usually on the first Friday of the month. It often causes sharp moves in the dollar and gold.'],
    ['CPI (inflation)', 'i', 6, 'The monthly measure of how fast prices are rising.',
      'Inflation data shapes interest-rate expectations, so it moves currencies.'],
    ['Fundamental analysis', 'i', 6, 'Judging a currency by the economy behind it: rates, growth, jobs, inflation.',
      'Fundamental traders follow news and central banks and think in days to months.'],

    // ---- Reading charts
    ['Technical analysis', 'b', 7, 'Judging price by studying charts and past behaviour.',
      'Technical traders believe patterns in price repeat. Tools include trend lines, support and resistance, and indicators.'],
    ['Candlestick', 'b', 7, 'A chart bar showing the open, close, high and low for one period.',
      'The thick body spans open to close. The thin lines (wicks) reach the high and low. Colours differ by platform, but usually green means it closed higher and red means lower.'],
    ['Timeframe', 'b', 7, 'How long each candle on your chart represents.',
      'M15 is 15 minutes, H1 one hour, H4 four hours, D1 one day. Shorter timeframes are noisier.'],
    ['Trend', 'b', 7, 'The general direction of price: up, down or sideways.',
      'Traders often try to trade with the trend rather than against it.'],
    ['Support and resistance', 'b', 7, 'Support: a price level where falls have paused. Resistance: a level where rises have stalled.',
      'Traders watch these levels because price often reacts there. They are zones, not exact lines.'],
    ['Range', 'b', 7, 'Price moving sideways between a floor and a ceiling. Also the distance between a period\'s high and low.',
      'In this app, "range" means the high minus the low during the session, measured in pips.'],
    ['Breakout', 'i', 7, 'Price pushing through support or resistance and continuing.',
      'Breakouts often come at a session open. Many fail and reverse, which is called a false breakout.'],
    ['Pullback (retracement)', 'i', 7, 'A short move against the trend before it continues.',
      'Traders use pullbacks to enter with the trend at a better price.'],
    ['Indicator', 'b', 7, 'A calculation drawn on a chart to help read price.',
      'Moving averages and RSI are common examples. Indicators lag price and do not predict it.'],
    ['Moving average (MA)', 'i', 7, 'The average price over a set number of candles, drawn as a smooth line.',
      'Price above a rising moving average suggests an uptrend. Common lengths are 20, 50 and 200.'],
    ['RSI', 'i', 7, 'An indicator from 0 to 100 that shows how stretched a move looks.',
      'Above 70 is often called overbought and below 30 oversold. Strong trends can stay in those zones a long time.'],
    ['Backtesting', 'a', 7, 'Testing a strategy on past prices to see how it would have done.',
      'It filters out bad ideas but cannot guarantee future results.'],

    // ---- Trading styles
    ['Day trading', 'b', 8, 'Opening and closing trades within the same day.',
      'No swap is paid because nothing is held overnight. Sessions and overlaps matter most to day traders.'],
    ['Scalping', 'i', 8, 'Very short trades, seconds to minutes, for small gains.',
      'It needs tight spreads and fast execution, so it is usually done in the busiest hours.'],
    ['Swing trading', 'i', 8, 'Holding trades for days to weeks to catch bigger moves.',
      'Swaps apply and gaps can happen over the weekend.'],

    // ---- In this app
    ['Trading window', 'b', 9, 'The hours you have chosen to trade, in your own clock.',
      'Setting one turns "I trade when I feel like it" into a rule. The app shows when you are inside it, what the market and news will be doing during it, and warns you before it starts. The journal then records whether each trade was inside or outside it, so you can see whether breaking your own hours costs you.'],
    ['Trading plan', 'b', 9, 'Your written rules for when, what and how much you trade.',
      'A plan usually covers the hours you trade, the pairs, how much you risk per trade, and when you stop for the day. It is easier to follow a rule you wrote when calm than to decide in the middle of a trade. The journal asks whether you followed yours.'],
    ['Peak, Good, Steady, Quiet, Closed', 'b', 9, 'The five levels the app uses to say how busy trading is right now.',
      'Peak (called Busiest time in the Beginner view): London and New York are both open. Good (Busy): London is open, or Tokyo and London overlap. Steady (Slower market): only Tokyo or only New York is open. Quiet: only Sydney is open, nothing is, or the markets that are open are on bank holidays. Closed: the weekend. They describe activity and costs. Busiest is not the same as safest, and none of them says whether a trade will win.'],
    ['Most active pairs', 'b', 9, 'Pairs where at least one currency has its home market open right now.',
      'Those pairs get the most trading, so spreads are usually lower. It is a shortlist of where the activity is, not a signal to buy or sell.'],
    ['Scheduled versus live activity', 'i', 9, 'The clock says how busy the market normally is. Live activity says how busy today really is.',
      'The headline level comes from the session schedule and bank holidays. Beside it, the app compares today\'s range with earlier sessions at the same point. When they disagree, for example a Peak on the clock but a quiet day, it tells you.', null, ['versus-usual']],
    ['Versus usual', 'i', 9, 'Whether the session is moving more or less than typical for this point in it.',
      'The app measures the high-to-low range since the session opened, then looks at the range over the same elapsed time in each of the last 10 sessions of the same name. If today is larger than at least 70% of them it says busier, and if larger than at most 30% it says quieter. Sessions with missing data are skipped, and it needs at least 5 to answer.',
      'Two hours into London, EUR/USD has a 45 pip range. If the last 10 London sessions had smaller ranges by that point in 8 cases, it is larger than 8 of 10 and counts as busier than usual.', ['range']],
    ['Chart time', 'b', 9, 'A setting for the clock your broker\'s or TradingView\'s chart shows.',
      'Once set, the app shows that time beside yours so the times you see here match the candles on your chart.', null, ['server-time-chart-time']],
  ];

  const slug = t => t.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
  g.GLOSSARY = RAW.map(([term, level, cat, short, long, example, see]) =>
    ({ id: slug(term), term, level, cat: CATS[cat], short, long, example: example || '', see: see || [] }));
  g.GLOSSARY_CATS = CATS;
  g.GLOSSARY_LEVELS = LEVELS;
})(window);
